# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
  db:
    image: postgres:15
    container_name: exam_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: examdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7
    container_name: exam_redis
    ports:
      - "6379:6379"
  api:
    build: .
    restart: always
    container_name: exam_api
    env_file:
      - .env.local
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./reports_data:/app/reports
    command: [
      "uvicorn",
      "app.main:app",
      "--host", "0.0.0.0",
      "--port", "8000",
      "--reload"
    ]
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
  worker:
    build: .
    container_name: exam_worker
    command: celery -A app.core.celery_app.celery worker --loglevel=info
    env_file:
      - .env.local
    environment:
    - PYTHONPATH=/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - .:/app
      - ./reports_data:/app/reports
volumes:
  postgres_data:
  reports_data:
