import {Inter} from "next/font/google"
import "../globals.css"
import ClientLayout from "@/components/ui/ClientLayout";

const inter = Inter({subsets: ["latin"]})

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({children,}: { children: React.ReactNode })
    {
    return (
        <html lang="en" className={inter.className}>
            <body>
                <ClientLayout>
                    <main className="p-4">{children}</main>
                </ClientLayout>
                {/*{!hideNavbar && <Navbar />}*/}
                {/*<main>{children}</main>*/}
            </body>
        </html>
    )
}
