import { Inter } from "next/font/google"
import { cn } from "@/lib/utils";
import "../globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={inter.classame}>
      <body>{children}</body>
    </html>
  )
}
