name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      # 1. Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Crear llave SSH
      - name: Setup SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      # 3. Deploy
      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          if [ -z "$EC2_HOST" ]; then echo "HOST EMPTY"; else echo "HOST OK"; fi
            if [ -z "$EC2_SSH_KEY" ]; then echo "KEY EMPTY"; else echo "KEY OK"; fi
            ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.EC2_HOST }} << 'EOF'

            echo "Pull latest code..."
            cd ~/exam-platform
            git config --global --add safe.directory /home/ec2-user/exam-platform
            git pull origin main

            echo "Stopping containers..."
            docker compose down

            echo "Building and starting containers..."
            docker compose -f docker-compose.yml up -d --build

            echo "Waiting for API..."
            for i in {1..10}; do
              if curl -f http://localhost:8000/health; then
                echo "API is ready"
                break
              fi
              echo "Waiting..."
              sleep 5
            done
            
            echo "Waiting for API container..."
            sleep 10

            echo "Running Alembic migrations..."
            docker compose exec -T api alembic upgrade head

            echo "Cleaning unused images..."
            docker system prune -f

            echo "Deploy complete"

          EOF
